### ISSUE TITLE
C-c C-~ is broken due to wrong lambda-list in slyfun

### ISSUE THREAD

**Issue by PuercoPop** [capitaomorte/sly#31]
Oi, Ok This is really weird and I'm pretty sure I must be missing something.

in contrib/slynk-mrepl.lisp the lambda list of sync-package-and-default-directory reads (&key ...) when it should read (&optional ...). The weird part is that according the vc-annonate and github's blame the last commit that modified that line 616f904a left it as optional so I am befuddled as to why when I updated sly I found &key there or in github's browser.

**Comment by capitaomorte** [comment]
I don't get it: as far as I remember these args were never `&optional`. They were mandatory and now they are `&key`. `contrib/sly-mrepl.el` is the only user of this slyfun and it uses it with `&key` args. 

(It should use `&optional` though, but that's another matter, and probably not terribly important. `&key` args are probably not good over the wire as they waste bytes...)

```
commit 616f904a496f9b624dd94ffd5bb64718203aba00
Author: João Távora <joaotavora@gmail.com>
Date:   Wed Nov 26 14:32:26 2014 +0000

    Make C-c C-z and C-c C-~ available in all of SLY
    
    * contrib/sly-mrepl.el (sly-mrepl): C-c C-z and C-c C-~ are useful
    in `sly-mode-map' too.
    (sly-mrepl--with-repl-for): Add edebug spec.
    (sly-mrepl-sync-package-and-default-directory): Work even when no
    directory and or package can be inferred. Add interactive
    spec.
    (sly-mrepl--eval-for-repl): Add docstring.
    
    * contrib/slynk-mrepl.lisp (eval-for-mrepl): Fix typo.
    (sync-package-and-default-directory): PACKAGE-NAME and DIRECTORY
    are now keyword args.
```

**Comment by PuercoPop** [comment]
I was getting the error pasted below error but after a make clean/all it works fine, it must have been a stray .elc. I thought that because sly asked to recompile the files I was in the clear. I should have been more thorough. Sorry about that. It appears to be working fine.   Btw, even though the args were never optional you do see the diff in the commit I linked showing changing them to optional? 

```
unknown &KEY argument: "#:kiosko-crawl/peru21"
   [Condition of type SB-INT:SIMPLE-PROGRAM-ERROR]

Restarts:
 0: [*ABORT] Return to SLY's top level.
 1: [ABORT] Abort thread (#<THREAD "sly-channel-1-mrepl-remote-1" RUNNING {1005FE2AB3}>)

Backtrace:
  0: (SLYNK-MREPL:SYNC-PACKAGE-AND-DEFAULT-DIRECTORY "#:kiosko-crawl/peru21" "/home/puercopop/quicklisp/local-projects/kiosko/crawlers/") [more,optional]
  1: ((LAMBDA NIL :IN SLYNK-MREPL:EVAL-FOR-MREPL))
  2: (SLYNK::CALL-WITH-BINDINGS ((*PACKAGE* . #<PACKAGE "COMMON-LISP-USER">) (* . #1=(DRAKMA CLSS PLUMP)) (**) (***) (/ #1#) (//) ...) #<CLOSURE (LAMBDA NIL :IN SLYNK-MREPL:EVAL-FOR-MREPL) {100872571B}>)
  3: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SLYNK-MREPL:EVAL-FOR-MREPL 1 (QUOTE SLYNK-MREPL:SYNC-PACKAGE-AND-DEFAULT-DIRECTORY) "#:kiosko-crawl/peru21" "/home/puercopop/quicklisp/local-projects/kiosko/crawlers/") ..
  4: (EVAL (SLYNK-MREPL:EVAL-FOR-MREPL 1 (QUOTE SLYNK-MREPL:SYNC-PACKAGE-AND-DEFAULT-DIRECTORY) "#:kiosko-crawl/peru21" "/home/puercopop/quicklisp/local-projects/kiosko/crawlers/"))
  5: (SLYNK:EVAL-FOR-EMACS (SLYNK-MREPL:EVAL-FOR-MREPL 1 (QUOTE SLYNK-MREPL:SYNC-PACKAGE-AND-DEFAULT-DIRECTORY) "#:kiosko-crawl/peru21" "/home/puercopop/quicklisp/local-projects/kiosko/crawlers/") "common-..
```

```
make check
...
Ran 186 tests, 179 results as expected, 6 unexpected, 1 skipped (2015-01-11 04:06:13-0500)
1 expected failures

6 unexpected results:
   FAILED  indent-30
   FAILED  indent-32
   FAILED  indent-84
   FAILED  indent-85
   FAILED  indent-86
   FAILED  sly-package-fu-test-package-used-p-test

1 skipped results:
  SKIPPED  autodoc-space-1

make: *** [check-fancy] Error 6
```

**Comment by capitaomorte** [comment]
@PuercoPop, I've seen that github diff, and everything seems fine. Aren't you confusing the very similarly named functions in `contrib/sly-mrepl.el` and `contrib/slynk-mrepl.lisp`? The first changed the args to optional and the second changed them to `&key`

Apropos the test failures, that's another matter. Those indentation tests have been failing in emacs 24.4 for a while now. But travis uses an older version of emacs that passes them. The `sly-package-fu-test-package-used-p-test` is yet another matter, can you describe how you reproduce the failure in a separate issue?

**Comment by PuercoPop** [comment]
Oi, sorry I wasn't clear, after I did make clean make all I have no issue at all.

**Comment by capitaomorte** [comment]
> I thought that because sly asked to recompile the files I was in the clear. I

You're talking about `sly.el` asking to recompile itself right? Yes, it does give that false impression, I never liked it. It should much rather invoke "make compile" or don't even check. Anyway, you can also update from MELPA which should avoid those issues. But if you do that it's a slightly more cumbersome to hack on SLY itself and open pull requests...
