### ISSUE TITLE
[Feature Request(?)]: propertize hook for mrepl output?

### ISSUE THREAD

**Issue by PuercoPop** [capitaomorte/sly#38]
I was attempting to port [slime-repl-ansi-colors.el](https://github.com/enriquefernandez/slime-repl-ansi-color/blob/master/slime-repl-ansi-color.el) to [sly](https://gist.github.com/PuercoPop/6bedf6275d11ead20e6a).

My idea was just to transform the string prior to writing it to the mrepl buffer. To do so my idea was to modify the string before it is inserted to the buffer by advising ```#'sly-mrepl--insert```. But *ansification* needs to happen after the sly-properties are applied. So before adding a hook, I tested my idea by adding ```(ansi-color-apply-on-region ,start-sym (sly-mrepl--mark))``` to the end of ```sly-mrepl--comiting-text```. But this approach has two pitfalls. First it also colorizes the input I submit and it doesn't colorized the output from the inferior-lisp as I learned that output is inserted via ```#'sly-mrepl--insert-output```.

I could achieve the desired functionality by doing something like (although it doesn't work idkw):
```elisep
(defun sly-repl-ansi-colorize (fun &rest args)
  (when sly-repl-ansi-color
    (with-current-buffer (sly-mrepl)
      (let ((inhibit-read-only t))
        (ansi-color-apply-on-region
         (save-excursion
           (cl-loop
            while (not (get-text-property (point) 'sly-mrepl--prompt))
            do (backward-char))
           (point))
         (marker-position  (sly-mrepl--mark)))))))

(advice-add 'sly-mrepl--insert-prompt :before #'sly-repl-ansi-colorize)
```
 However I think it could be a useful addition to provide a hook to propertize the text returned from the inferior process.

Btw I am in no urgent need for ansi-colors in the sly-mrepl, I was just trying to write a simple sly-contrib to get the hang of it.

**Comment by capitaomorte** [comment]
I've pushed a prototype implementation, so have a look. In your new contrib, it should be as easy as adding `ansi-color-apply' as one of `sly-mrepl-output-filter-functions', which mimics `comint-preoutput-filter-functions` directly (and is actually initialized to that variable's value). I tried it with this silly example

```elisp
(add-hook 'sly-mrepl-output-filter-functions
          (lambda (string)
            (replace-regexp-in-string "bla" (propertize "BLA" 'face 'highlight) string)))
```

**Comment by PuercoPop** [comment]
Interface/API-wise it is perfect imho. Indeed the functionality is enabled with a simple (add-hook 'sly-mrepl-output-filter-functions 'ansi-color-apply).

I now know why the last snippet "did not" work. It did, but ansi-colors.el uses *font-lock-face*s to apply styles. I remember vaguely from issue #1 that font-lock-mode should be disabled in the mrepl.

The colors are revealed are seen as soon as I activate font-lock-mode via M-x. Ieaving font-lock-mode on in Emacs 24.4.1 seems to work without problems. Although it is too soon to tell. Did the conflict with font-lock-mode and mrepl manifested only in emacs 24.3?

**Comment by capitaomorte** [comment]
> Did the conflict with font-lock-mode and mrepl manifested only in emacs 24.3?

I don't know anymore: at any rate it only manifested itself in your configuration, and I never really figured out why. I've gone back and forth between turning it on and off in sly-mrepl and I might reanalyse and decide to turn it back on. Anyway, in your contrib, you could try just changing the `font-lock-face` property that `ansi-color-apply` applied to `face`.

**Comment by PuercoPop** [comment]
I think it would be prudent to turn it off by default (having the sly-mrepl-mode-hook default to nil) to see if the bug manifests in someone else's configuration during the beta period.

Great suggestion about the face! With it the contrib now [works](https://gist.github.com/PuercoPop/6bedf6275d11ead20e6a)! Do you want me to send PR adding the contrib or would you prefer it to serve as a third-party extension demo (as the missing sly-hello-world)?

One unrelated question, if I want to create a new slynk-channel (which is a mailbox over a listener iiuc) would the correct way be to call ```#'slynk-mrepl:create-mrepl?``` if so is the remote-id supposed to be the listener-id?

**Comment by capitaomorte** [comment]
> would you prefer it to serve as a third-party extension demo (as the missing sly-hello-world)?

Yes precisely! naturally, it would be better if you could come up with some kind of Slynk-side functionality for it :-) so that it could become a nice example. If only some helper functions to let users ansificate whatever they print to the standard output streams. Ideally some global ansification strategy exclusive for hooking onto, say "print-unreadable-object", but only when the SLY MREPL is the target. Or some other fancyness you think of.

> One unrelated question, if I want to create a new slynk-channel (which is a mailbox over a listener iiuc) would the correct way be to call #'slynk-mrepl:create-mrepl? if so is the remote-id supposed to be the listener-id?

A channel is just an asynchronous "no-reply-needed" alternative to regular slyfun's (basically, a mailbox, yes). The remote channel exists on either end. It's actually not a very pretty abstraction unless you need that behaviour (and a "good" REPL needs it).

The `listener` class is independent from the `channel` class. When a `listener` is created, you pass it two streams, `in` and `out`. It sandboxes an environment of bindings in which the standard streams are secretly bound to the streams you passed in, for both output and input. *whenever you're inside the `with-listener` macro*, printing to `*standard-out*` will print to the stream you passed into the listener at creation time. If that stream is a some slynk creature that sends messages to Emacs, you get them in Emacs. If it's a socket stream (the dedicated) variety, that sends utf-8 text to emacs, you also get them in Emacs.

It just so happens that an `mrepl` mixes in both classes, so a `slynk-mrepl::mrepl` object *is* both.

**Comment by capitaomorte** [comment]
I forgot to ask what you are trying to do, perhaps then I can be of better help.

**Comment by PuercoPop** [comment]
I will create the repo with a readme on the weekend then. I'd rather not bikeshed more on ansi colors as its marginal utility, to colorize [prove](https://github.com/fukamachi/prove), has already been achieved.

I have two contribs in mind. First is to start have a [cl-async](https://github.com/orthecreedence/cl-async) event loop running in the slynk side and the other is to make a websocket proxy so I can write the sly-side in the browser (sly.js).

The first one is the one that is useful, as it would ease the development when using [blackbird](https://github.com/orthecreedence/blackbird)'s async versions of defun/let/etc (adefun/alet/etc). Currently when I want to test code in the REPL I have to wrap it in an event loop. Like an animal. I'm not sure where it would be the best place to put the event loop, either add it as an option to the prefered communication or to limit it on a per mrepl basis (that would put the event loop inside a channel right?). Ivan4th has written a version for [SLIME](https://github.com/orthecreedence/cl-async/blob/master/src/repl.lisp), but I think that sly could improve on it using its multiple repls.

So to understand better how the inner pieces of slynk work to be able write a correct version of the first idea, I thought a good pet project would be something like a browser front-end to slynk, akin to [sn.lisp-daemon](https://github.com/snmsts/sn.lisp-daemon). So my idea is write a proxy to expose slynk through websockets. A while back I wrote [a version](https://gist.github.com/PuercoPop/e502441885bf66ae43cf) that I know is wrong, specially the client-connected part. 

Btw thank you for all your help.

**Comment by PuercoPop** [comment]
FYI: I've created the demo repo here: https://github.com/PuercoPop/sly-repl-ansi-color. Let me know if the you want something added to the readme.
