### ISSUE TITLE
C-h m fails in the mrepl

### ISSUE THREAD

**Issue by PuercoPop** [capitaomorte/sly#40]
### Steps to Reproduce
1. Switch to an mrepl buffer
2. C-h m

If I attempt to reproduce in a clean sly (w/o my config) C-h m works fine.

However inspecting the backtrace it appears the issue is that ```#'sly-mrepl-mark``` is called in the context of the current-buffer being ```#<buffer  prin1>```. idk why would C-h m result in a call to sly-mrepl-mark but I'll post a PR with a fix right now.

### Backtrace
```
Debugger entered--Lisp error: (wrong-type-argument processp nil)
  process-mark(nil)
  sly-mrepl--mark()
  sly-mrepl--shortcut-location-p()
  (if (sly-mrepl--shortcut-location-p) cmd)
  (lambda (cmd) (if (sly-mrepl--shortcut-location-p) cmd))(sly-mrepl-shortcut)
  documentation(sly-mrepl-mode)
  describe-mode()
  call-interactively(describe-mode nil nil)
  command-execute(describe-mode)

```

**Comment by PuercoPop** [comment]
What is weirder, if I jump to the source of ```#'sly-mrepl--mark``` the error is fixed!

**Comment by capitaomorte** [comment]
This was related to a particular finicky hack used sometimes in Emacs. The `:filter` trick for a keybinding, whereby the keybinding is sometimes active and sometimes not active, depending on some buffer-local condition. For some reason, your version of `describe-mode` evaluated the keybinding filters in the temporary buffer for printing the help buffer, not the original mode being described. I fixed it with a simpler, more localized test.

**Comment by PuercoPop** [comment]
I'd swear one of this days I'm going to delete all my an emacs config and start from 0. Anyhow thanks for the prompt fix.
