### ISSUE TITLE
Undefined function: slynk::make-compilation-result

### ISSUE THREAD

**Issue by ruricolist** [capitaomorte/sly#43]
- On Clozure;
- running the latest Sly;
- with sly-retro disabled;
- when I use `sly-compile-defun`, I get an error that `slynk::make-compilation-result` is undefined. 

If I evaluate the `defstruct` form in `sly.el` directly, then everything works fine, so I imagine there's probably some kind of subtle evaluation-order problem here.

**Comment by capitaomorte** [comment]
Hi @ruricolist. You do mean the 

```lisp
(defstruct (:compilation-result
             (:type list) :named)
  notes
  (successp nil :type boolean)
  (duration 0.0 :type float)
  (loadp nil :type boolean)
  (faslfile nil :type (or null string)))
```

in `slynk/slynk.lisp`, not `sly.el` right? 

If so, I can't reproduce this, at least without more details. Can you give a reproduction recipe starting from `emacs -Q`, setting `inferior-lisp-program` accordingly and then `M-x sly`?

I tried with Clozure Common Lisp 
```
Welcome to Clozure Common Lisp Version 1.9-r15759  (DarwinX8664)!
```
The most I can guess is that there is a stale file issue, but the default ASDF-based loading method should theoritically take care of that. Have you tried clearning your ASDF cache? Mine lives in 
```
$HOME/.cache/common-lisp/ccl-1.9-f96-macosx-x64
```

**Comment by ruricolist** [comment]
Yes, I meant `slynk.lisp`. (Sorry.)

The problem is actually completely different that I first thought; it's a bad interaction between Slynk and Swank. (A dependency of a dependency of a dependency was loading Swank without my realizing.)

Starting with a clean cache and the latest Sly from Github:

```lisp
ccl --no-init
(load #p"~/quicklisp/setup.lisp")
(ql:quickload :slynk)
(fboundp 'slynk::make-compilation-result) ; => t
(ql:quickload :swank)
(fboundp 'slynk::make-compilation-result) ;=> nil
```

The problem here is that (for some reason) the structure is named by a keyword. 

In Clozure, when a structure is defined, the first thing that happens is a call to `ccl::remove-structure-defs`, which looks up the structure's name in a `eq` hash table and then calls `fmakunbound` on any associated constructors, accessors, &c. This means, when `(defstruct (:compilation-result ....))` is evaluated in Swank, it completely blows away Slynk's definition.

This might, strictly speaking, be a bug in Clozure, but my suggestion (unless there's some deep reason why the structure's name has to be a keyword) would be to just change the name to an ordinary symbol.

**Comment by capitaomorte** [comment]
> but my suggestion (unless there's some deep reason why the structure's name has to be a keyword) would be to just change the name to an ordinary symbol. 

Makes sense. The struct name had the `:` since its inception in 2008 (64f01d83c15ab320dc255088d74fb59bcc0f6a7b), but it appears to have been a spurious decision.
