### ISSUE TITLE
Sly-note intertwined with inferior-lisp's standard-output

### ISSUE THREAD

**Issue by PuercoPop** [capitaomorte/sly#45]
As test case, (ql:system-apropos "zip")
The ; No values notes appears amist of the resuts from quicklisp.

![image](https://cloud.githubusercontent.com/assets/387111/7478766/7ba18f20-f322-11e4-8205-ca141e92a05d.png)

**Comment by capitaomorte** [comment]
Hmm, I can't reproduce this. Moreover this is something I remember spending some time with. 

Can you reproduce it from a clean `emacs -Q` run? Also give me your OS (ubuntu, I suppose), emacs and sbcl versions.

**Comment by capitaomorte** [comment]
UUuups nevermind I just reproduced it. Only happens sometimes

**Comment by capitaomorte** [comment]
Commit b5be63bad seems to have subtly introduced this, or at least made it more evident, as I can't reproduce with any `sly-mrepl.el` version before it.

**Comment by PuercoPop** [comment]
The screenshot posted above is on -Q. It seems to be a timing issue as it doesn't always get intertwined in the same place.

**Comment by capitaomorte** [comment]
> It seems to be a timing issue as it

Yes it is, but it's clearly identified. I'm working on a proper fix, but a quick one is to replace `sly-mrepl--insert-note` with `sly-mrepl--insert` on line 486 of `contrib/sly-mrepl.el`

**Comment by capitaomorte** [comment]
I pushed a fix. Can you give it a go? keep an eye out for regressions, though I tested more or less well.

**Comment by PuercoPop** [comment]
The Fix works as intended as far I can see. :+1:

**Comment by capitaomorte** [comment]
Actually, a little problem cropped up when the evaluation errors. Should be fixed.
