### ISSUE TITLE
About `slynk:*use-dedicated-output-stream*` 

### ISSUE THREAD

**Issue by ruricolist** [capitaomorte/sly#46]
In the course of trying to use Sly over ssh I discovered that `slynk:*use-dedicated-output-stream*` isn't being used anywhere. To actually prevent a dedicated output stream from being created, you have to set `slynk-mrepl:*use-dedicated-output-stream*`. 

This may just be a case of the documentation being out of date, but the existence of two symbols with the same name, one of which is documented and exported from Slynk, but never defined or used, and one which is used, but not documented, is confusing.

**Comment by capitaomorte** [comment]
That's right. A docfix is in order. I'll get to it asap.
