### ISSUE TITLE
sly-xref-next-line deletes the xref window

### ISSUE THREAD

**Issue by dgutov** [capitaomorte/sly#47]
1. Move point to a `(format ...)` call, press `M-.`, see the `*sly-xref*` buffer pop up with multiple destinations.

2. Press `n` there (or `p`). See the xref window deleted, point jumps to the destination that was rendered on the next (previous) line.

Expected result: the next location is displayed in the "other" window, but the xref window stays, and the focus stays in it.

Emacs master, Sly from MELPA.

**Comment by capitaomorte** [comment]
SLY's xref's semantics have changed slightlly from SLIME's, but the behaviour you describe does sound like a bug. I'll look into it.

Do you think xref.el in emacs is mature enough to have SLY's xref functionality be based on it? I need it do two things:

1. Let xref results buffer go into a special major mode and change the name
2. The xref.el library must be backward compatible to emacs 24.4

**Comment by capitaomorte** [comment]
Actualy, I just remembered the way I implemented it. On an xref there is "go to source" and "show source" (the context menu reveals this). 

`v` on an xref "shows" your the source the way you expect it to, whereas `.` (and `RET`) "goes" to the source. 

`n` and `p`, which I personally don't use, both implement "go to source". So I guess they should implement "show" according to you. Please confirm.

By the way, can `xref.el` handle this difference?

**Comment by dgutov** [comment]
> Do you think xref.el in emacs is mature enough to have SLY's xref functionality be based on it?

Not yet. I have some breaking changes planned. And after, we should look and see what's missing.

> Let xref results buffer go into a special major mode and change the name

You mean other than xref--xref-buffer-mode? You can't do that yet, but that may be easy to add. Where would you specify the major mode and the buffer name, though? In xref-find-function?

> The xref.el library must be backward compatible to emacs 24.4

We'll see closer to the release of 25, but this might be problematic. The implementation depends on cl-generic, which is new and now in GNU ELPA either.

> So I guess they should implement "show" according to you. Please confirm.

I believe so. There's no reason to deviate from SLIME there.

> By the way, can xref.el handle this difference?

Depends on what you mean by that. It does have separate commands for those two actions.

**Comment by capitaomorte** [comment]
Dmitry Gutov <notifications@github.com> writes:

>> Do you think xref.el in emacs is mature enough to have SLY's xref functionality be based on it?
>
> Not yet. I have some breaking changes planned. And after, we should look and see what's missing.

OK, I'll wait.

>> Let xref results buffer go into a special major mode and change the name
>
> You mean other than xref--xref-buffer-mode? You can't do that yet, but
> that may be easy to add. Where would you specify the major mode and
> the buffer name, though? In xref-find-function?

I thought I might do it with `xref-show-xrefs-function', as you
mentioned somewhere in emacs-devel. Won't that work.

>> The xref.el library must be backward compatible to emacs 24.4
>
> The implementation depends on cl-generic, which is new and now in GNU ELPA either.

, but it depends only on pcase and cl-lib. I could bundle it as
well. Perhaps it's silly, but I still entertain the possibility of
bundling external libraries in `lib`, so that an easy (m)ELPA-less
install is possible. SLIME has historically done this.

>> So I guess they should implement "show" according to you. Please confirm.
>
> I believe so. There's no reason to deviate from SLIME there.

Agree.

>> By the way, can xref.el handle this difference?
>
> Depends on what you mean by that. It does have separate commands for those two actions.

Great that's what I menat.

**Comment by dgutov** [comment]
> I thought I might do it with `xref-show-xrefs-function', as you mentioned somewhere in emacs-devel. Won't that work.

It will, however where would you set it? In sly-mode? Globally? One can call a `sly-` command from any buffer, if they so desire.

> Perhaps it's silly, but I still entertain the possibility of bundling external libraries in `lib`, so that an easy (m)ELPA-less install is possible. SLIME has historically done this.

That doesn't sound like a very good idea to me. Aside from avoiding ELPA (why?), the current xref.el is problematic:

* It assigns bindings at the top level.
* The default backend is etags, defined in etags.el.
* The same default backend uses a function in xref.el that relies on certain CEDET functionality that was fixed (or improved) recently in master. So far it's been API-compatible, though.

**Comment by dgutov** [comment]
cdaadb4e6e348de9406e2680bb0579a5fc2afcb1 fixed the `n` and `p` behavior, but made other things different from SLIME (and xref.el):

* RET doesn't jump to the location anymore. It performs the "show" action.
* SPC, surprisingly, goes to the source.

**Comment by capitaomorte** [comment]
> It will, however where would you set it? In sly-mode? 

Yes

> Globally? 

No. buffer-locally

> One can call a sly- command from any buffer, if they so desire.

So I guess it could be let-bound in `sly-edit-definition` then. Won't that work?

> That doesn't sound like a very good idea to me. Aside from avoiding ELPA (why?),

Some reasons actually. SLIME has traditionally only depended on Emacs. Traditionally, users have also been encouraged to use trunk checkouts to simplify development I suppose. It's also installable through quicklisp, which doesn't handle dependencies afaik. A lot of people use this. For me personally, it's great to have a simple `emacs -Q -L . -l sly-autoloads.el` to reproduce bugs. 

But I guess this is rowing against the tide. What do you recommend? Especially interested in making `package.el` prefer a SLY developer's git checkout. There's a way to do it, right?

> It assigns bindings at the top level.

Hmmm, that would have to be worked around, indeed. Any change this could be changed in xref.el so that it becomes just a library?

> The default backend is etags, defined in etags.el.
> The same default backend uses a function in xref.el that relies on certain CEDET functionality that was fixed (or improved) recently in master. So far it's been API-compatible, though.

That wouldn't be a problem if I could work around the previous problem and ensure only the sly backend is used in `sly-edit-definition`. `M-x xref-find-definitions` would be a problem though.

**Comment by dgutov** [comment]
> So I guess it could be let-bound in sly-edit-definition then. Won't that work?

Yep, but then you'd need to have a wrapper for every xref command. Which is better than not using a common infrastructure a all, but still less than ideal.

`xref-show-xrefs-function`, so far, has been intended as a customization point for the user. Vitalie Spinu, for instance, declared his intention to implement a tabulated-list-based view. For users who would prefer it, it will be hard to reconcile with Sly wanting to use a different major mode.

Why don't we try to settle on something like this:
* Sly supplies a new `xref-show-xrefs-function`. The user is free to use it, or not.
* The xref buffer name generation, whatever backend is used, can take into account the name of the backend, the invoked action, and maybe even the input. I'm a bit worried about proliferation of those buffers, though, and how each of them defines its own `next-error-function`.

If there are valuable features we're going to miss this way, you should bring them up on emacs-devel.

> Some reasons actually. SLIME has traditionally only depended on Emacs.

Of course. It started when there was no ELPA anyway.

> Especially interested in making package.el prefer a SLY developer's git checkout. There's a way to do it, right?

Not that I know of. It might be a good subject for a feature request, though.

> Any change this could be changed in xref.el so that it becomes just a library?

The solution would be to release a slightly-different versions of xref and cl-generic on GNU ELPA (and maintain them there). You could also bundle those, I suppose.

**Comment by phikal** [comment]
Has anything changed on this front, making it possible to reuse the built-in xref for Sly?

**Comment by joaotavora** [comment]
No, but I would be very grateful if someone takes on this task! I can
provide support/guidance but I don't have time to undertake it myself.
