### ISSUE TITLE
sly-inspect-fetch-all does nothing

### ISSUE THREAD

**Issue by tuhdo** [capitaomorte/sly#49]
To reproduce:

- Insert a lot of things into a hash table.
- Inspect it
- Run the command bound to `>`
- Nothing happens.

**Comment by tuhdo** [comment]
Right now I have to set `sly-inspector-limit` to very high number to view all. The problem is that when trying to get the button at point, `sly` returns `nil` and cannot execute the inner code to fetch all buttons.

**Comment by capitaomorte** [comment]
Thanks for reporting!

**Comment by capitaomorte** [comment]
Thanks, it should be fixed now
