### ISSUE TITLE
C-u M-x Sly-apropos doesn't allow one to select all packages

### ISSUE THREAD

**Issue by PuercoPop** [capitaomorte/sly#53]
Because the interactive function uses completing read one is unable to select blank for all packages.

Also a couple of suggestions. I think that negative argument should only prompt for package. And the apropos result buffer could include the lambda list next to the symbol name for functions and macros.

**Comment by capitaomorte** [comment]
Thanks for the bug report. Should be fixed. Using the default completion method, you have the option to choose "(none)". With other completion methods, just leave the field blank.

**Comment by capitaomorte** [comment]
Now, here's why I never use `sly-apropos`: Because `sly-apropos-all` uses the package designator name in the search string as well, so I just use an expression that starts with the package designator and a regexp, which is automatically supported if you have `quickload`ed `cl-ppcre`.

**Comment by capitaomorte** [comment]
I liked your suggestions and implemented them. Check it out.

**Comment by PuercoPop** [comment]
Oi thanks for the prompt fix and enhancements!

However there is a bug in the current implementation. For example, M-x sly-apropos and type zero. Slynk tries to get the lambda-list of a condition.

**Comment by capitaomorte** [comment]
Thanks, should be fixed now!

On Fri, Jul 17, 2015 at 10:20 PM, Javier Olaechea <notifications@github.com>
wrote:

> Oi thanks for the prompt fix and enhancements!
>
> However there is a bug in the current implementation. For example, M-x
> sly-apropos and type zero. Slynk tries to get the lambda-list of a
> condition.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/capitaomorte/sly/issues/53#issuecomment-122421356>.
>



-- 
João Távora
