### ISSUE TITLE
Recent Emacs commit breaks Sly

### ISSUE THREAD

**Issue by ruricolist** [capitaomorte/sly#63]
A recent commit to `help.el` ([this one](https://lists.gnu.org/archive/html/emacs-diffs/2015-10/msg00365.html)) makes it impossible to connect to Lisp in Sly.

Trying to connect brings up the debugger, with output like this:

```
Debugger entered: (("Error in timer" sly-attempt-connection (#<process inferior-lisp> nil 11) (error "Unrecognized usage format")))
  (condition-case data (progn (let* ((syms (mapcar (function car) env)) (vals (mapcar (function cdr) env)) (body (function (lambda nil (apply fun args)))) (binds nil)) (while syms (setq binds (cons (list (car-safe ...) (list ... ...)) binds))) (eval (list (quote let) binds (list (quote funcall) (list (quote quote) body)))))) ((debug error) (debug nil (list "Error in timer" fun args data))))
  sly-timer-call(sly-attempt-connection ((sly-ignore-protocol-mismatches)) #<process inferior-lisp> nil 11)
  apply(sly-timer-call (sly-attempt-connection ((sly-ignore-protocol-mismatches)) #<process inferior-lisp> nil 11))
  timer-event-handler([t 22074 31605 57218 nil sly-timer-call (sly-attempt-connection ((sly-ignore-protocol-mismatches)) #<process inferior-lisp> nil 11) nil 623999])
```

The problem happens while loading `sly-stickers.el`, in `help-add-fundoc-usage` from in `help.el`. In particular, `help-add-fundoc-usage` balks at the docstring for `sly-stickers--pretty-describe-recording`, because it has a newline in it.

I'm not sure whether the bug is that Emacs is being too strict, or `cl-lib` is not escaping enough, but I wanted to document this here for anyone else having the problem.

**Comment by capitaomorte** [comment]
I can't reproduce this on w32 yet since I can't find that recent a build (and building it myself is crazy). I'll have a look at home if I can.

Another thing is intriguing me: `sly-stickers--pretty-describe-recording` doesn't have a docstring (perhaps you have added one :-)? ) 

EDIT: Ah but it has an arglist, a cl-only arglist and one that has a optional arg with `\n` as a default value. Hmmm, looks like a bug in emacs, right? Can you report it or should I?

**Comment by ruricolist** [comment]
I just reported it to the Emacs bug tracker.

**Comment by capitaomorte** [comment]
Thanks, I've just seen it here: http://lists.gnu.org/archive/html/bug-gnu-emacs/2015-11/msg00230.html
