### ISSUE TITLE
How can i disable return value shortening?

### ISSUE THREAD

**Issue by axionix** [capitaomorte/sly#70]
Multi-line return values are not shown in full, instead showing an ellipsis. I'd like to disable this feature if possible.
For example, this is supposed to show 4 rows, when it only shows the first:

```lisp
#<1.0 0.0 0.0 0.0 ..>

**Comment by capitaomorte** [comment]
> For example, this is supposed to show 4 rows, when it only shows the first:

Hmm, what exactly "is supposed to show 4 rows"?

In general, the SLY REPL is affected by the standard CL pretty printer variables like `*PRINT-LENGTH*`, what value do you have for this variable? Perhaps you can try assigning different values to it...

Separate lines are (currently) reserved for CL's multilple return values, otherwise it would be confusing to read 
```
(values (produce-multi-line-return-value) (produce-single-line-return-value))
```

**Comment by axionix** [comment]
I would like the functionality of SLIME, where my 4x4 pretty-printed matrix object is shown in its entirety.

**Comment by capitaomorte** [comment]
_what_ 4x4 pretty-printed matrix object?? :-) What is the expression producing said matrix? Can you post it here?

Do you mean something like this?
```
TEST> (make-array '(4 4) :initial-element 0)
#2A((0 0 0 0) (0 0 0 0) (0 0 0 0) (0 0 0 0))
TEST> 
```

This is a 4x4 array that is shown in its entirety...

**Comment by axionix** [comment]
https://github.com/axionix/ax.game/blob/master/math-matrix.lisp#L63-L72

any matrix object is printed differently than SLIME, as shown in my opening post.

I've also seen this shortening elsewhere, though I can't remember where.

**Comment by capitaomorte** [comment]
I'm very sorry, but in your opening post you don't say anything about matrixes, you say "this" is supposed to show four rows, and then you show this

```
#<1.0 0.0 0.0 0.0 ..>
```

I could not possibly guess you meat matrixes: But, looking at your code, I it uses `set-pprint-dispatch`, so that explains it.

There is no currently support for (non-standard) multi-line pprint dispatchers, but I can look into adding it.

**Comment by axionix** [comment]
I'm sorry for the lack of explaining what I mean. I'm in the middle of 10 things at once and my mind isn't working correctly as a result.

I see, if you could in the future sometime, that would be great.

By the way, I have noticed it for other things too, such as really large arrays. Try '(20 20).

Thanks :)

**Comment by capitaomorte** [comment]
Can you try this patch for a while. It seems to work OK for me, but I want someone to give it some testing

```diff
diff --git a/contrib/slynk-mrepl.lisp b/contrib/slynk-mrepl.lisp
index 8159703..14e5543 100644
--- a/contrib/slynk-mrepl.lisp
+++ b/contrib/slynk-mrepl.lisp
@@ -155,7 +155,9 @@ (defun backreference-reader-tests ()
 
 (defun make-results (objects)
   (loop for value in objects
-        collect (list (slynk::to-line value)
+        collect (list (slynk::without-printing-errors
+                          (:object value :stream nil)
+                        (prin1-to-string value))
                       (1- (length *history*)))))
 
 (defun mrepl-eval (repl string)
```

**Comment by axionix** [comment]
That patch works great. Thanks :)

**Comment by axionix** [comment]
Not that I care, but my colors get messed up part way through printing a large array though:

https://i.imgur.com/bG7T6Q8.png

**Comment by capitaomorte** [comment]
> That patch works great. Thanks :)

Good to know. I've commited it

> Not that I care, but my colors get messed up part way through printing a large array though:

Hmmm, can you point to the extension that you're using for fancy rainbow parenthesis? perhaps it gives up after some lists? Or Emacs own fontification system does.

**Comment by axionix** [comment]
That's what I suspected too, but copying it to a file buffer does not.

I'm using rainbow-delimiters: https://github.com/axionix/dotfiles/blob/master/.emacs.d/init.el#L429
