### ISSUE TITLE
Can't open an inspector on an empty prompt

### ISSUE THREAD

**Issue by PuercoPop** [capitaomorte/sly#77]
On a fresh sly, Typing `C-c I` on the REPL results in an error no sexp near point message from `sly-sexp-at-point 'interactive`. Also if one then goes back a character and types C-c I, it pre-fills the prompt with the prompt, (ej. CL-user). Some screenshots to clarify

# First Issue

![image](https://cloud.githubusercontent.com/assets/387111/12465257/28c4c57e-bf9b-11e5-9ed4-566a902cb67c.png)

# Second Issue

![image](https://cloud.githubusercontent.com/assets/387111/12465271/362dedc6-bf9b-11e5-8c80-78c6699a235b.png)

Related to #72

**Comment by capitaomorte** [comment]
Yeah, I've seen it. Let me see if I can fix it quickly...

**Comment by capitaomorte** [comment]
The second issue is not a bug imo, and if it were, I don't think it deserves fixing  :-)

**Comment by PuercoPop** [comment]
Certainly not a bug, but it is a UX issue from my perspective. A minor one albeit.
