### ISSUE TITLE
fuzzy/flex completion display

### ISSUE THREAD

**Issue by kaiserprogrammer** [capitaomorte/sly#81]
display of completions is on 2 lines because the last "-" is wrapping on the new line.

key bindings missing for completion selection like arrow keys (maybe others)

**Comment by capitaomorte** [comment]
Thanks for the report. I'll have a look.  There is some instabilitiy with
the new functionality. The key binding problem is easy to fix, but for the
other, can you give a concrete reproduction recipe? Perhaps a screenshot.

Thanks,
Joao

**Comment by kaiserprogrammer** [comment]
![2016-03-27-164504_scrot](https://cloud.githubusercontent.com/assets/955653/14065899/0daab57a-f43c-11e5-8a27-bdfabd44d6be.jpg)

**Comment by capitaomorte** [comment]
Funny stuff. I'm glad I asked you for the screenshot because that's not
what I had in mind at all. Anyway, I can't reproduce it. What are the exact
versions of sly and emacs that you are using?

**Comment by kaiserprogrammer** [comment]
emacs: 24.5.1
sly: 20160324.1012

It happens when left or right fringes are deactivated. fringe-mode select no-fringes should do the trick.

**Comment by capitaomorte** [comment]
@kaiserprogrammer, sorry for the delay. I still can't reproduce it. It might have to do with the `truncate-lines` variables.

Anyway, due to this comment in the docstring of `window-width`:

```
(window-width &optional WINDOW PIXELWISE)
...
Note that the returned value includes the column reserved for the
continuation glyph.
```

I've decided to use `(1- (window-wdith))` when calculating the whitespace filling.
