### ISSUE TITLE
Trouble with the sly-fuzzy removal

### ISSUE THREAD

**Issue by PuercoPop** [capitaomorte/sly#83]
Hi Joao,

After updating sly, I've run into issues were `sly-fuzzy-complete-symbol` is when pressing tab in the REPL.
And after updating sly-company also when sly-company tries to complete.
I have verified that the `completion-at-point-functions` variable doesn't include the removed function.
Its value is `(sly-complete-filename-maybe sly-complete-symbol)`
When tracing execution of `sly--completion-in-region-function` (w/ edebug) the form `(funcall function nil nil 'sly--identify)` appears to return a value that includes sly-fuzzy-complete-symbol.
It seems the issue may be a cached value? :confused: 
I have done make clean to remove all of *.elc But the problem persists. Any idea what is going on?

```elisp
Result: (closure ((cached-arg) (cached-result) (fn . sly-fuzzy-complete-symbol) t) (string pred command) (let ((--cl-all-- (function (lambda nil (cl-first (if (and cached-arg (string= cached-arg string)) cached-result (setq cached-arg string cached-result (funcall fn string)))))))) (cond ((eql command (quote sly--identify)) t) ((eql command (quote metadata)) (list (quote metadata) (cons (quote display-sort-function) (function identity)) (cons (quote annotation-function) (function (lambda (completion) (get-text-property 0 (quote sly--annotation) completion)))))) ((memql command (quote (t))) (funcall --cl-all--)) ((memql command (quote (nil))) (let ((all (funcall --cl-all--))) (if (and all (null (cdr all))) (if (string-prefix-p string (car all)) t string) (and all string)))) (t (if (and (consp command) (eq (car command) (quote boundaries))) (completion-boundaries string (funcall --cl-all--) pred (cdr command)) nil)))))
````

Would appreciate any hints,
  Thanks in advance

**Comment by PuercoPop** [comment]
Forgot to add, on a clean install it works perfectly

**Comment by capitaomorte** [comment]
There may be more than one effect at play here. First make sure you have no stale elc files in your configuration.

The presence of `sly-fuzzy-complete-symbol` may be a symptom of that.

**Comment by capitaomorte** [comment]
The second problem, is probably that sly-company needs to be updated to use the new (more powerful, simpler, yet still obviously buggier) completion backend.

**Comment by capitaomorte** [comment]
Oh I just read in your original report that you got rid of your .elc files. Look at your configuraiton, too, there may be stale `.elc` files there too.

**Comment by capitaomorte** [comment]
What is the value of the variable `sly-complete-symbol-function` in your problematic config?

**Comment by PuercoPop** [comment]
The issue was was sly-complete-symbol-function was customized in my custom.el. Weird I don't remeber ever customizing it.

**Comment by capitaomorte** [comment]
This is going to be a problem for more users though. Damn, I shouldn't have used the same variable name. Perhaps I should change it, any suggestions?

**Comment by PuercoPop** [comment]
I think that a beefier entry on news.md would suffice. Including a light troubleshooting section and specifying which ac/company version/commit is needed prior or after which sly commit.

**Comment by capitaomorte** [comment]
Hmmm you're right I guess. I wonder if I haven't fixed `sly-company` by fixing SLY for `sly-ac` also

**Comment by capitaomorte** [comment]
Hmmm, close but not cigar, it uses another interface directly. More than 10 years of history = :baggage_claim:

I'll take a look tomorrow.
