### ISSUE TITLE
slynk-completion's qualified-matching incorrectly assumes that all accessible symbols have a home-package

### ISSUE THREAD

**Issue by PuercoPop** [capitaomorte/sly#87]
When that happens completion breaks. This happens for example after loading parenscrip (due to its re-export-symbols). This happens on SBCL 1.3.2 (not on CCL).

```lisp
;; After loading parenscript the following snippet returns
(let (result)
  (do-all-symbols (s)
    (unless (symbol-package s)
      (push s result)))
  result)

;; => (#:TYPE #:REMOVE #:WRITE #:OPEN #:CLASS-NAME #:CLOSE #:METHOD #:DECLARE #:LENGTH)
```

**Comment by capitaomorte** [comment]
Well if it's true it does sound like the run-of-the-mill incorrect assumption. I'll take a pull request discarding those symbols then...

How are they printed by the way? Also, can you provide a quick recipe for producing symbols in these conditions.

**Comment by PuercoPop** [comment]
A short way is

```lisp
(defpackage #:foo
  (:use)
  (:export #:bar))

(defpackage #:fubar
  (:use)
  (:import-from #:foo #:bar)
  (:export #:bar))

(delete-package (find-package "FOO"))
```

Afterwards the symbol bar from, the now nonexistent package, foo is now accessible but has no home-package.

They are printed as uninterned symbols. This is mentioned in the CLHS entry of [unintern](http://www.lispworks.com/documentation/HyperSpec/Body/f_uninte.htm)

> Use of unintern can result in a symbol that has no recorded home package, but that in fact is accessible in some package. Common Lisp does not check for this pathological case, and such symbols are always printed preceded by #:.

The term for these symbols appears to be [apparently uninterned](http://www.lispworks.com/documentation/HyperSpec/Body/26_glo_a.htm#apparently_uninterned)

There is some pertinent discussion on [#lisp](http://log.irc.tymoon.eu/freenode/lisp?around=2016-04-19T22:25:16&types=mnaot#1461104716)


What do you mean discarding 'those' symbols? The symbols above or aparently uninterned symbols?

A quick fix would be to provide a another symbol iteration construct that excludes symbols without a homepackage like shown below. Should I prepare the PR?

```lisp
(defmacro do-all-symbols-with-home-package ((var) &body body)
  `(do-all-symbols (,var)
     (when (symbol-package ,var)
       ,@body)))
```

**Comment by capitaomorte** [comment]
So, I did a slightly simplified version of your latest commit and _commited in your name_. (Let me know if you don't appreciate this kind of thing in the future.)

**Comment by PuercoPop** [comment]
> (Let me know if you don't appreciate this kind of thing in the future.)

Its ok. I think it is the correct etiquette to do so as pull requests as they stand don't really favor back and forth code exchange before merging. :disappointed:
